"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Course, DailyReview, Goal, PriorityTier, Store, Task, TaskStatus, id, today } from "../lib/domain";
import { generateDailyPlan } from "../lib/planner";
import { loadStore, saveStore } from "../lib/storage";

const blank: Store = { goals: [], courses: [], tasks: [], sessions: [], reviews: [], schedule: [], availability: {} };
const labels: Record<TaskStatus, string> = { TODO: "待开始", IN_PROGRESS: "进行中", DONE: "已完成", OVERDUE: "已逾期", SKIPPED: "已跳过", BLOCKED: "受阻", CANCELLED: "已取消" };
export default function Home() {
  const [store, setStore] = useState<Store>(blank); const [ready, setReady] = useState(false); const [date, setDate] = useState(today());
  const [view, setView] = useState<"today" | "goals" | "courses" | "schedule" | "tasks" | "review">("today");
  useEffect(() => { setStore(loadStore()); setReady(true); }, []);
  useEffect(() => { if (ready) saveStore(store); }, [store, ready]);
  const available = store.availability[date] ?? 120;
  const plan = useMemo(() => generateDailyPlan({ date, availableMinutes: available, tasks: store.tasks, goals: store.goals, courses: store.courses, schedule: store.schedule }), [store, date, available]);
  const plannedMinutes = plan.items.reduce((total, task) => total + task.plannedMinutes, 0);
  const update = (fn: (old: Store) => Store) => setStore((old) => fn(old));
  const addGoal = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get("title") || "").trim(); if (!title) return; update(s => ({ ...s, goals: [...s.goals, { id: id(), title, priority: Number(f.get("priority")), targetDate: String(f.get("targetDate") || "") || undefined }] })); e.currentTarget.reset(); };
  const addCourse = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get("title") || "").trim(); if (!title) return; update(s => ({ ...s, courses: [...s.courses, { id: id(), title, goalId: String(f.get("goalId") || "") || undefined, priority: Number(f.get("priority")), weeklyTargetMinutes: Number(f.get("minutes")) }] })); e.currentTarget.reset(); };
  const addTask = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get("title") || "").trim(); if (!title) return; update(s => ({ ...s, tasks: [...s.tasks, { id: id(), title, courseId: String(f.get("courseId") || "") || undefined, goalId: String(f.get("goalId") || "") || undefined, priorityTier: String(f.get("tier")) as PriorityTier, status: "TODO", plannedDate: String(f.get("plannedDate") || date), dueDate: String(f.get("dueDate") || "") || undefined, plannedMinutes: Number(f.get("minutes")), actualMinutes: 0 }] })); e.currentTarget.reset(); };
  const setStatus = (task: Task, status: TaskStatus) => {
    const blockedReason = status === "BLOCKED" ? window.prompt("请填写阻塞原因")?.trim() : undefined;
    if (status === "BLOCKED" && !blockedReason) return;
    update(s => ({ ...s, tasks: s.tasks.map(t => t.id === task.id ? { ...t, status, blockedReason } : t) }));
  };
  const saveReview = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const review: DailyReview = { date, wins: String(f.get("wins")), blockers: String(f.get("blockers")), reflection: String(f.get("reflection")), tomorrowAdjustment: String(f.get("adjustment")), energyLevel: Number(f.get("energy")) }; update(s => ({ ...s, reviews: [...s.reviews.filter(r => r.date !== date), review] })); };
  if (!ready) return <main className="shell">正在加载学习系统…</main>;
  return <main className="shell"><header><div><p className="eyebrow">PERSONAL LEARNING OS · V0.1.1</p><h1>把今天学好。</h1><p className="sub">目标 → 计划 → 执行 → 记录 → 复盘 → 调整</p></div><nav>{([['today','今日'],['goals','目标'],['courses','课程'],['schedule','课表'],['tasks','任务'],['review','复盘']] as const).map(([v, n]) => <button key={v} className={view === v ? "active" : ""} onClick={() => setView(v)}>{n}</button>)}</nav></header>
  {view === "today" && <section><div className="datebar"><label>计划日期 <input type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label>可用分钟 <input type="number" min="0" value={available} onChange={e => update(s => ({ ...s, availability: { ...s.availability, [date]: Math.max(0, Number(e.target.value) || 0) } }))} /></label></div><div className="stats"><Stat label="可用时间" value={`${available} 分钟`} /><Stat label="固定课程" value={`${plan.scheduledMinutes} 分钟`} /><Stat label="已安排" value={`${plannedMinutes} 分钟`} /><Stat label="剩余容量" value={`${plan.remainingMinutes} 分钟`} /></div><h2>今日计划</h2>{plan.items.length ? <div className="plan">{(["MUST", "SHOULD", "COULD"] as PriorityTier[]).map(tier => <div key={tier}><h3 className={`tier ${tier.toLowerCase()}`}>{tier}</h3>{plan.items.filter(x => x.priorityTier === tier).map(task => <article className="task" key={task.id}><div><strong>{task.title}</strong><small>{task.plannedMinutes} 分钟 · {task.selectionReason}</small></div><div className="actions"><select value={task.status} onChange={e => setStatus(task, e.target.value as TaskStatus)}>{Object.entries(labels).map(([v, n]) => <option key={v} value={v}>{n}</option>)}</select><button onClick={() => { const recordedAt = new Date().toISOString(); update(s => ({...s, sessions: [...s.sessions, { id:id(), taskId:task.id, courseId:task.courseId, startedAt:recordedAt, endedAt:recordedAt, actualMinutes:25, note:"专注学习" }], tasks:s.tasks.map(t => t.id===task.id ? {...t, status:"IN_PROGRESS", actualMinutes:t.actualMinutes+25} : t)})); }}>记录 25 分钟</button></div></article>)}</div>)}</div> : <Empty text="还没有可安排任务。请先添加目标、课程或任务。" />}</section>}
  {view === "goals" && <section className="two"><div><h2>长期目标</h2>{store.goals.map(g => <article className="card" key={g.id}><strong>{g.title}</strong><small>优先级 {g.priority} · 目标日期 {g.targetDate || "未设置"}</small></article>)} {!store.goals.length && <Empty text="从一个清晰、长期的学习目标开始。" />}</div><form className="card form" onSubmit={addGoal}><h3>新建目标</h3><input name="title" placeholder="例如：通过雅思 7 分" required/><label>优先级 <input name="priority" type="number" min="1" max="5" defaultValue="3" /></label><label>目标日期 <input name="targetDate" type="date" /></label><button>保存目标</button></form></section>}
  {view === "courses" && <section className="two"><div><h2>课程</h2>{store.courses.map(c => <article className="card" key={c.id}><strong>{c.title}</strong><small>每周目标 {c.weeklyTargetMinutes} 分钟 · 优先级 {c.priority}</small></article>)} {!store.courses.length && <Empty text="课程可关联到长期目标，并提供每周学习时长目标。" />}</div><form className="card form" onSubmit={addCourse}><h3>新建课程</h3><input name="title" placeholder="例如：法语 A2" required/><select name="goalId"><option value="">不关联目标</option>{store.goals.map(g => <option key={g.id} value={g.id}>{g.title}</option>)}</select><label>优先级 <input name="priority" type="number" min="1" max="5" defaultValue="3" /></label><label>每周分钟 <input name="minutes" type="number" min="1" defaultValue="180" /></label><button>保存课程</button></form></section>}
  {view === "schedule" && <ScheduleView store={store} update={update} />}
  {view === "tasks" && <section className="two"><div><h2>任务池</h2>{store.tasks.map(t => <article className="card" key={t.id}><strong><span className={`badge ${t.priorityTier.toLowerCase()}`}>{t.priorityTier}</span>{t.title}</strong><small>{labels[t.status]} · 计划 {t.plannedMinutes} 分钟 / 实际 {t.actualMinutes} 分钟 · {t.plannedDate || "未排期"}</small></article>)} {!store.tasks.length && <Empty text="任务应尽量小到可以在一次学习时段内完成。" />}</div><form className="card form" onSubmit={addTask}><h3>新建任务</h3><input name="title" placeholder="例如：完成第 3 单元听力练习" required/><select name="tier" defaultValue="SHOULD"><option>MUST</option><option>SHOULD</option><option>COULD</option></select><select name="courseId"><option value="">不关联课程</option>{store.courses.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select><label>计划分钟 <input name="minutes" type="number" min="5" step="5" defaultValue="30" /></label><label>计划日期 <input name="plannedDate" type="date" defaultValue={date}/></label><label>截止日期 <input name="dueDate" type="date" /></label><button>保存任务</button></form></section>}
  {view === "review" && <section className="two"><div><h2>{date} 每日复盘</h2><div className="stats"><Stat label="计划" value={`${plannedMinutes} 分钟`} /><Stat label="实际" value={`${store.sessions.filter(s => s.startedAt.slice(0,10) === date).reduce((n,s) => n+s.actualMinutes,0)} 分钟`} /></div><p className="hint">未完成的任务会保留在候选池，明日生成计划时会优先考虑逾期及 MUST 任务。</p></div><form className="card form" onSubmit={saveReview}><h3>记录今天</h3><textarea name="wins" placeholder="今天做得好的部分"/><textarea name="blockers" placeholder="阻塞或困难"/><textarea name="reflection" placeholder="复盘与收获"/><textarea name="adjustment" placeholder="明日调整，例如：只安排 90 分钟"/><label>精力（1–5）<input name="energy" type="number" min="1" max="5" defaultValue="3"/></label><button>保存复盘</button></form></section>}
  </main>;
}
function Stat({ label, value }: {label:string; value:string}) { return <div className="stat"><small>{label}</small><strong>{value}</strong></div>; }
function Empty({ text }: {text:string}) { return <p className="empty">{text}</p>; }

function ScheduleView({ store, update }: { store: Store; update: (fn: (old: Store) => Store) => void }) {
  const add = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const courseId = String(f.get("courseId")); if (!courseId) return; const start = String(f.get("start")); const end = String(f.get("end")); const [sh, sm] = start.split(":").map(Number); const [eh, em] = end.split(":").map(Number); const minutes = (eh * 60 + em) - (sh * 60 + sm); if (!Number.isFinite(minutes) || minutes < 5) return; update(s => ({ ...s, schedule: [...s.schedule, { id: id(), courseId, weekday: Number(f.get("weekday")), startTime: start, endTime: end, minutes, kind: String(f.get("kind")) as "CLASS" | "SELF_STUDY" | "RESERVED" }] })); e.currentTarget.reset(); };
  const weekday = ["周日", "周一", "周二", "周三", "周四", "周五", "周六"];
  return <section className="two"><div><h2>固定课程表</h2>{store.schedule.map(block => <article className="card" key={block.id}><strong>{weekday[block.weekday]} · {block.startTime}–{block.endTime}</strong><small>{store.courses.find(c => c.id === block.courseId)?.title || "已删除课程"} · {block.kind} · {block.minutes} 分钟</small></article>)} {!store.schedule.length && <Empty text="固定课程与自主学习时段会从每日可用时间中扣除。" />}</div><form className="card form" onSubmit={add}><h3>添加固定时段</h3><select name="courseId" required><option value="">选择课程</option>{store.courses.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select><select name="weekday">{weekday.map((day, n) => <option key={day} value={n}>{day}</option>)}</select><select name="kind"><option value="CLASS">固定上课</option><option value="SELF_STUDY">固定自学</option><option value="RESERVED">保留时段</option></select><label>开始 <input name="start" type="time" defaultValue="19:00" required /></label><label>结束 <input name="end" type="time" defaultValue="20:00" required /></label><button>保存时段</button></form></section>;
}
